version: 2
updates
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "src/test/**"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
